print('''
THANK YOU ALL FOR WATCHING

A MASSIVE THANK YOU TO ALL THE JAMS AND THE INFINITY WORKS TEAM FOR ALL THE HELP THEY'VE GIVEN ME IN THE DEVELOPMENT OF THIS PROJECT

HOPE YOU ENJOYED!!!

ALSO A BIG CONGRATULATIONS TO THE REST OF THE JAMS FOR ALL THEIR AMAZING PRENSENTATIONS TODAY  

ANY QUESTIONS?
''')